### ISSUE TITLE
Pre Demo Todo List

### ISSUE THREAD

**Issue by AlexLLKong** [Vero-Ventures/job-bank#78]
- [ ] setup node-cron to run cron jobs locally
- [ ] ensure payment flow works
- [ ] jobsite themes
- [ ] finish competitor scraper
- [ ] remove tor from jobbank.gc.ca email scraper
- [ ] create final production deployment in vercel
- [ ] admin stuff 
- [ ] write documentation
- [ ] course deliverables
